import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Chart from "@/components/Chart";
import Population from "@/data/charts/population";
import Population2 from "@/data/charts/population2";
import Accordion from "@/components/Accordion";
// import Chapter1 from "@/components/Chapter1";
import Chapter2 from "@/data/chapter2";
import Chapter from "@/components/Chapter";


export default function Countefactualfutures() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>


      <div className="mainwrapper">
        <Chapter chapter= {Chapter2} >
        </Chapter>
      {/* <Chapter1>
      </Chapter1> */}
      </div>
      
    </>
  );
}
